<a href="https://colab.research.google.com/github/omartinez6/ml-zoomcamp/blob/main/homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

## Q1. Pandas version
What's the version of Pandas that you installed?

In [2]:
version = pd.__version__
version

'2.1.4'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-27 23:15:34--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.06s   

2024-09-27 23:15:34 (5.16 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [4]:
laptops = pd.read_csv('laptops.csv')
laptops.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

## Q2. Records count
How many records are in the dataset?

In [5]:
records = laptops.shape
records

(2160, 12)

## Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [6]:
brands = laptops.Brand.nunique()
brands

27

## Q4. Missing values
How many columns in the dataset have missing values?

In [7]:
missing = laptops.isnull().sum()[laptops.isnull().sum() > 0]
missing.count()

3

## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [8]:
max_price = laptops[laptops.Brand == 'Dell']['Final Price'].max()
max_price

3936.0

## Q6. Median value of Screen
* Find the median value of Screen column in the dataset.
* Next, calculate the most frequent value of the same Screen column.
* Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
* Now, calculate the median value of Screen once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

In [9]:
median_screen = laptops.Screen.median()
median_screen

15.6

In [10]:
freq_screen = laptops.Screen.mode()
laptops.Screen.fillna(freq_screen)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [11]:
new_median_screen = laptops.Screen.median()
new_median_screen

15.6

## Q7. Sum of weights
* Select all the "Innjoo" laptops from the dataset.
* Select only columns RAM, Storage, Screen.
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Compute the inverse of XTX.
* Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [12]:
innjoo = laptops[laptops.Brand == 'Innjoo'][['RAM','Storage','Screen']]
x = np.array(innjoo)
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [13]:
xt = np.transpose(x)
xt

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [14]:
xtx = xt.dot(x)
xtx

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [15]:
inverse = np.linalg.inv(xtx)
inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [17]:
w = inverse.dot(xt).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [18]:
total = w.sum()
total

91.2998806299555